### ISSUE TITLE
SPSS Export is interrupted with error `Error: Invalid input type, expected 'integer' actual 'double'`

### ISSUE THREAD

**Issue by nuernbergerc** [nukleus-ecu/epicodr#14]
i followed our step-by-step guide for the use of the package 

i tested the spss export with suep data (test data plus a data set i got from you) and it did not export a bunch of tables to sav format

these were: scv, stv1, stv2, pomp, prom0, prom2, prom4, prom5, prom8, prom8k, prom9, prom9k, prom12, prom12k, prom13, prom13k, qs, vp, vpfs and the data frame we created in the primary coding functions ecu_who_scale

the following error message appeared: Error: Invalid input type, expected 'integer' actual 'double'

with pop and hap test data, it worked fine

@mrainers could you please check, why it did not work correctly for suep? 

after i looked into the function i understood that it did not export ecu_who_scale because it was not included in export_options
is there a way to include this data frame in the export, too?

**Comment by nuernbergerc** [comment]
@mrainers we talked about this topic last week, are there any news?

**Comment by mrainers** [comment]
I tested it with "tsExport_Testdata_SUEP_2022-06-27.zip"

I managed to track down the problem to the table promext. The table could not be exported to spss, because of troubles with the classes of the variables "brs_2", "brs_4" and "brs_6". Originaly those where of type "double". But the primary_coding_suep() function changed them to integer class. When the prepare for export function adds the class attributes "haven_labelled_spss" and "haven_labelled" this produces a conflict. For some reason it doesn't like integers, when exporting.

A solution might be that the prepare_for_spss_export() function ensures, that the variables that where converted to "haven_labelled" class are also converted to double. 

That the other files are missing is because the export process stops at the error and tables that come alphabeticly after promext, wheren't exported anymore.

That  "ecu_who_scale" table isn't exported is another Issue though.

**Comment by mrainers** [comment]
Further exploration shows that write_sav can actually write labelled interger but get's confused when the labels and missing values are of type double/numeric. 
This problem is caused by manually adding the "labels" and "na_values" class attributes to the variable. The variables should be better reinicciated with the "labelled_spss()" function.

**Comment by mrainers** [comment]
The variables were converted to integer by the primary_coding_suep() function  (See issue #18). However the labels that where added to the variable by the "prepare_for_spss_export()" function are doubles. That is what creates the conlict. I already have a fix for that. I just need to test it and then push it into the gitlab project.
